# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Yarn CLI
    # You may pin to the exact commit or the version.
    # uses: CultureHQ/actions-yarn@661c6f3a66041c2432bcfb78096b9207304614c8
      uses: CultureHQ/actions-yarn@v1.0.1
    - run: yarn install --pure-lockfile
    - run: yarn build-lib
    - run: yarn build
